# This is a basic workflow to help you get started with Actions
# Literally taken from kade engine github, sorry kade

name: HTML5 Build CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        #with:
          #haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: install haxelib crap
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib haxe -y
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install hxcpp > nul
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git hscript https://github.com/YoshiCrafter29/hscript-improved.git
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git hscript-improved https://github.com/YoshiCrafter29/hscript-improved
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib install hxcpp-debug-server
          haxelib list
      - name: compile ig
        run: |
          haxelib run lime build html5
          
      - uses: actions/upload-artifact@v2
        with:
          name: HTML5 Build
          path: export/release/html5/bin
